//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocalForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int PostId { get; set; }
        public string Message { get; set; }
        public int TopicId { get; set; }
        public byte[] PostTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
